name: Continuous release

on: [push, pull_request]

jobs:
  appimage-x86_64:
    name: AppImage x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build AppImage
        run: |
          export ARCH=x86_64 APPIMAGE_EXTRACT_AND_RUN=1
          bash -xe build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage x86_64
          path: ReText*.AppImage*

  appimage-i386:
    name: AppImage i386 (cross)
    runs-on: ubuntu-latest
    container: i386/ubuntu:bionic
    steps:
      # git is needed before the checkout, so we have to install the dependencies first
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git build-essential wget
      - uses: actions/checkout@v2
      - name: Build AppImage
        run: |
          export ARCH=i386 APPIMAGE_EXTRACT_AND_RUN=1
          bash -xe build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage i386
          path: ReText*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - appimage-x86_64
      - appimage-i386
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        uses: marvinpinto/action-automatic-releases@latest
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: true
          title: "Continuous build"
          files: |
            **/ReText*.AppImage*

